age = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]
gender = ['male', 'female']
heights = ["140 cm", "145 cm", "150 cm", "155 cm", "160 cm", "165 cm", "170 cm", "175 cm", "180 cm", "185 cm", "190 cm", "195 cm", "200 cm", "205 cm", "210 cm", "215 cm", "220 cm", "225 cm", "230 cm", "240 cm"]
professions = {
    "good_chars": [
        "Doctor",
        "Nurse",
        "Surgeon",
        "Paramedic",
        "Pharmacist",
        "Biologist",
        "Microbiologist",
        "Chemist",
        "Engineer",
        "Mechanical Engineer",
        "Electrical Engineer",
        "Civil Engineer",
        "Programmer",
        "Software Developer",
        "IT Specialist",
        "Cybersecurity Expert",
        "Farmer",
        "Agricultural Specialist",
        "Veterinarian",
        "Builder",
        "Carpenter",
        "Electrician",
        "Plumber",
        "Mechanic",
        "Pilot",
        "Soldier",
        "Police Officer",
        "Firefighter",
        "Survival Instructor",
        "Hunter",
        "Fisherman",
        "Cook",
        "Chef",
        "Nutritionist",
        "Psychologist",
        "Teacher",
        "Professor",
        "Mathematician",
        "Physicist",
        "Geologist",
        "Architect",
        "Radiologist",
        "Radiation Specialist",
        "Logistics Manager",
        "Transport Specialist",
        "Radio Operator",
        "Communications Expert",
        "Security Guard",
        "Scout",
        "Navigator",
        "Map Maker",
        "Medic",
        "Field Medic",
        "Military Engineer",
        "Weapons Technician",
        "Drone Operator",
        "Electric Technician",
        "Water Systems Engineer",
        "Waste Management Specialist",
        "Environmental Scientist",
        "Criminologist",
        "Rescue Worker",
        "Emergency Dispatcher",
        "Sailor",
        "Ship Engineer",
        "Diver",
        "Wilderness Guide",
        "Blacksmith",
        "Tool Maker",
        "Tailor",
        "Locksmith",
        "Data Analyst",
        "Statistician",
        "Economist",
        "Accountant",
        "Supply Chain Manager",
        "Warehouse Manager",
        "Quality Control Specialist",
        "Drone Repair Technician",
        "Robotics Engineer",
        "AI Engineer",
        "Machine Learning Engineer",
        "Structural Engineer",
        "Hydrologist",
        "Meteorologist",
        "Seismologist",
        "Energy Technician",
        "Solar Panel Technician",
        "Wind Energy Engineer",
        "Translator",
        "Interpreter",
        "Crisis Manager",
        "Negotiator",
        "Strategist",
        "Ethnobotanist",
        "Medicinal Plant Expert",
        "Survival Medic",
        "Tactical Planner"
    ],

    "bad_chars": [
        "Influencer",
        "TikTok Creator",
        "Instagram Model",
        "YouTuber",
        "Streamer",
        "Celebrity Stylist",
        "Fashion Model",
        "Makeup Artist",
        "Beauty Blogger",
        "Fashion Designer",
        "DJ",
        "Nightclub Manager",
        "Stand-up Comedian",
        "Actor",
        "Movie Director",
        "Photographer",
        "Art Critic",
        "Painter",
        "Poet",
        "Writer",
        "Journalist",
        "Social Media Manager",
        "Marketing Influencer",
        "Brand Ambassador",
        "Event Planner",
        "Wedding Planner",
        "Luxury Travel Blogger",
        "Hotel Reviewer",
        "Food Blogger",
        "Fashion Consultant",
        "Makeup Influencer",
        "Hair Stylist",
        "Barista",
        "Waiter",
        "Cashier",
        "Retail Worker",
        "Salesman",
        "Luxury Brand Consultant",
        "Perfume Tester",
        "Jewelry Designer",
        "Clown",
        "Magician",
        "Circus Performer",
        "Dancer",
        "Singer",
        "Pop Star",
        "Rapper",
        "Gamer",
        "Esports Commentator",
        "Game Reviewer",
        "Anime Reviewer",
        "Reality Show Contestant",
        "Dating Coach",
        "Life Coach",
        "Motivational Speaker",
        "Astrologer",
        "Fortune Teller",
        "Tarot Reader",
        "Crystal Healer",
        "Energy Healer",
        "Yoga Influencer",
        "TikTok Dancer",
        "Vlogger",
        "Selfie Photographer",
        "Travel Influencer",
        "Meme Page Admin",
        "Celebrity Gossip Blogger",
        "Pop Culture Analyst",
        "Street Fashion Blogger",
        "Mall Manager",
        "Cinema Worker",
        "Theme Park Worker",
        "Casino Dealer",
        "Gambling Advisor",
        "Lottery Seller",
        "Cruise Ship Entertainer",
        "Flight Attendant",
        "Influencer Manager",
        "PR Specialist"
    ]
}

hobbies = {
    "good_chars": [
        "Fishing",
        "Hunting",
        "Gardening",
        "First aid training",
        "Fire making",
        "Knots tying",
        "Camping",
        "Water purification",
        "Archery",
        "Repairing tools",
        "Cooking",
        "Foraging",
        "Survival training",
        "Wood carving",
        "Building shelters",
        "Swimming",
        "Running",
        "Strength training",
        "Martial arts",
        "Shooting practice",
        "Reading survival manuals",
        "Navigation practice",
        "Map reading",
        "Fishing net making",
        "Sewing",
        "Knitting",
        "Animal tracking",
        "Hiking",
        "Orienteering",
        "Firearm maintenance",
        "Emergency drills",
        "Radio communication practice",
        "Basic medicine practice",
        "Herbal medicine study",
        "Plant identification",
        "Solar panel setup practice",
        "Mechanical repair practice",
        "Car maintenance",
        "Metal working",
        "Blacksmithing basics",
        "Knife sharpening",
        "Water collection systems",
        "Team coordination games",
        "Puzzle solving",
        "Strategic games (chess)",
        "Memory training",
        "Disaster simulation games",
        "Engineering hobby projects",
        "DIY building",
        "Welding practice",
        "Energy saving techniques",
        "Trap building",
        "Self-defense training",
        "Fire safety drills"
    ],

    "bad_chars": [
        "Watching TikTok",
        "Scrolling social media",
        "Collecting stickers",
        "Doing makeup",
        "Celebrity gossip",
        "Online shopping",
        "Watching reality shows",
        "Selfie photography",
        "Following fashion trends",
        "Watching Netflix all day",
        "Gaming (non-competitive survival skills)",
        "Watching drama series",
        "Browsing memes",
        "Sleeping long hours",
        "Party lifestyle",
        "Nightclub going",
        "Drinking alcohol as hobby",
        "Luxury shopping",
        "Influencer content creation",
        "Streaming random content",
        "Watching YouTube shorts endlessly",
        "Shopping haul videos",
        "Fashion try-ons",
        "Pranking people",
        "Scrolling reels endlessly",
        "Celebrity stalking",
        "Horoscope reading",
        "Tarot card obsession",
        "Crystal collecting (non-useful)",
        "Talking about gossip",
        "Beauty vlogging",
        "Makeup tutorials",
        "Dance challenges",
        "Lip-sync videos",
        "Fashion blogging",
        "Travel influencer posting",
        "Food blogging (non-survival)",
        "Luxury lifestyle posting",
        "Car show-off content",
        "Collecting luxury items",
        "Online arguing",
        "Political debating (non-productive)",
        "Watching sports only",
        "Fantasy roleplay games",
        "Idle mobile gaming",
        "Unboxing videos",
        "Watching prank videos",
        "Celebrity fan pages",
        "Dream interpretation obsession"
    ]
}

health = {
    "good_chars": [
        "Healthy",
        "Strong immune system",
        "Athletic condition",
        "Excellent stamina",
        "Good vision",
        "Good hearing",
        "Fast healing body",
        "High pain tolerance",
        "No chronic diseases",
        "Excellent physical strength",
        "Flexible body",
        "Well-nourished",
        "Mentally stable",
        "High stress resistance",
        "Good cardiovascular health",
        "Strong lungs",
        "Balanced diet condition",
        "Good reflexes",
        "Stable blood pressure",
        "High endurance",
        "Good bone density",
        "Quick recovery from illness",
        "Good sleep quality",
        "Strong mental resilience",
        "Healthy weight",
        "No allergies",
        "Good coordination",
        "Strong metabolism",
        "Good digestion",
        "Physically active lifestyle"
    ],

    "bad_chars": [
        "Asthma",
        "Diabetes",
        "Broken leg",
        "Blind in one eye",
        "Deaf in one ear",
        "Severe allergies",
        "Heart condition",
        "Chronic pain",
        "Anxiety disorder",
        "Depression",
        "Weak immune system",
        "Asthma attacks",
        "Mobility issues",
        "Wheelchair user",
        "Epilepsy",
        "Migraines",
        "Poor eyesight",
        "Color blindness",
        "Chronic fatigue",
        "Obesity",
        "Malnutrition",
        "Severe back pain",
        "Arthritis",
        "Respiratory disease",
        "Infection prone",
        "Slow healing",
        "Blood disorder",
        "Nerve damage",
        "Hearing loss",
        "Sleep disorder"
    ]
}

items = {
    "good_chars": [
        "Knife",
        "First aid kit",
        "Water bottle",
        "Gun (no ammo)",
        "Flashlight",
        "Rope",
        "Map",
        "Radio",
        "Battery pack",
        "Compass",
        "Multi-tool",
        "Survival backpack",
        "Canned food",
        "Water filter",
        "Firestarter kit",
        "Sleeping bag",
        "Tent",
        "Axe",
        "Shovel",
        "Crowbar",
        "Sewing kit",
        "Solar charger",
        "Walkie-talkie",
        "Gas mask",
        "Medical kit",
        "Notebook",
        "Pen",
        "Emergency blanket",
        "Portable stove",
        "Fuel canister",
        "Wrench",
        "Hammer",
        "Screwdriver set",
        "Fishing rod",
        "Fishing net",
        "Binoculars",
        "Knife sharpener",
        "Steel wire",
        "Tarpaulin",
        "Emergency food rations",
        "Water container",
        "Signal mirror",
        "Whistle",
        "Thermometer",
        "Duct tape",
        "Portable generator",
        "Metal pot",
        "Cooking utensils",
        "Survival guide book",
        "Paracord"
    ],

    "bad_chars": [
        "Rubber duck",
        "Fancy hat",
        "Scented candle",
        "Luxury perfume",
        "Mirror",
        "Plush toy",
        "Chocolate bar (melted)",
        "Deck of cards",
        "Magnet",
        "Feather",
        "Broken umbrella",
        "Sunglasses at night",
        "Empty notebook",
        "Toy sword",
        "Bottle of perfume",
        "Old VHS tape",
        "Glitter",
        "Plastic tiara",
        "Decorative rock",
        "Fake mustache",
        "Balloon",
        "Party mask",
        "Makeup kit",
        "Hair dryer",
        "Straightener",
        "Fashion magazine",
        "Luxury watch (broken)",
        "Designer handbag",
        "Gold-plated phone case",
        "Selfie stick",
        "Tripod",
        "Ring light",
        "Bluetooth speaker (no battery)",
        "VR headset (no power)",
        "Gaming console",
        "Laptop (dead battery)",
        "Tablet (cracked screen)",
        "Headphones (broken)",
        "Perfume collection",
        "Art painting kit",
        "Fancy wine glass",
        "Decorative vase",
        "Crown prop",
        "Stage microphone",
        "Inflatable pool toy",
        "Christmas decoration",
        "Party confetti",
        "Fashion shoes (high heels)",
        "Fake diamond necklace"
    ]
}

special_traits = {
    "good_chars": [
        "Knows a secret bunker location",
        "Has a hidden stash of food",
        "Can speak 5 languages",
        "Very lucky",
        "Trusted by all",
        "Expert survival instincts",
        "Quick decision maker",
        "Natural leader",
        "Excellent memory",
        "Calm under pressure",
        "High pain tolerance",
        "Expert at navigation",
        "Knows first aid perfectly",
        "Can read people easily",
        "Great problem solver",
        "Highly adaptable",
        "Fast learner",
        "Strong intuition",
        "Good at teamwork",
        "Can build tools from scrap",
        "Knows how to hunt animals",
        "Can start fire in any condition",
        "Excellent strategist",
        "Knows military tactics",
        "Good at organizing groups",
        "Can repair almost anything",
        "Strong survival instincts",
        "Knows plant medicine",
        "Can identify edible plants",
        "Excellent focus under stress"
    ],

    "bad_chars": [
        "Former criminal",
        "Afraid of darkness",
        "Infected but no symptoms",
        "Extremely unlucky",
        "Hates everyone",
        "Very selfish",
        "Panic under pressure",
        "Poor decision maker",
        "Easily distracted",
        "Always lies",
        "Cannot keep secrets",
        "Fear of authority",
        "Clumsy in critical moments",
        "Overconfident",
        "Paranoid",
        "Trusts nobody",
        "Afraid of blood",
        "Aggressive personality",
        "Easily manipulated",
        "Slow thinker",
        "Avoids responsibility",
        "Addicted to attention",
        "Constantly complains",
        "Bad at teamwork",
        "Refuses to follow rules",
        "Impulsive behavior",
        "Easily scared",
        "Always argues",
        "Cannot handle stress",
        "Mentally unstable"
    ]
}

phobias = {
    "good_chars": [
        "Fear of luxury items",
        "Fear of modern technology",
        "Fear of crowded places",
        "Fear of loud noises (helps stay quiet)",
        "Fear of open spaces (stays indoors safely)",
        "Fear of strangers (careful social behavior)",
        "Fear of risks (careful decision making)",
        "Fear of fire (prevents accidents)",
        "Fear of wasting resources",
        "Fear of contamination",
        "Fear of infection",
        "Fear of reckless behavior",
        "Fear of overconfidence",
        "Fear of leaving safety zone",
        "Fear of unnecessary fights",
        "Fear of noise attracting danger",
        "Fear of trusting unknown people",
        "Fear of dark forests (avoids danger zones)",
        "Fear of storms (prepares early)",
        "Fear of unknown food sources"
    ],

    "bad_chars": [
        "Fear of darkness",
        "Fear of heights",
        "Fear of water",
        "Fear of blood",
        "Fear of isolation",
        "Fear of insects",
        "Fear of loud noises (paralyzing panic)",
        "Fear of fire (cannot cook or survive)",
        "Fear of small spaces",
        "Fear of strangers (unable to cooperate)",
        "Fear of survival tools",
        "Fear of weapons",
        "Fear of leaving shelter",
        "Fear of food scarcity discussions",
        "Fear of responsibility",
        "Fear of leadership roles",
        "Fear of medicine",
        "Fear of injured people",
        "Fear of darkness in caves",
        "Fear of night time",
        "Fear of forests",
        "Fear of animals",
        "Fear of rain",
        "Fear of wind",
        "Fear of silence",
        "Fear of being alone",
        "Fear of group decisions",
        "Fear of survival situations",
        "Fear of unknown environments",
        "Fear of danger signs"
    ]
}
