age = [5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99, 100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116, 117, 118, 119, 120]
gender = ['male', 'female']
heights = ["140 cm", "145 cm", "150 cm", "155 cm", "160 cm", "165 cm", "170 cm", "175 cm", "180 cm", "185 cm", "190 cm", "195 cm", "200 cm", "205 cm", "210 cm", "215 cm", "220 cm", "225 cm", "230 cm", "240 cm"]
professions = [
    "Doctor",
    "Teacher",
    "Engineer",
    "Lawyer",
    "Nurse",
    "Architect",
    "Programmer",
    "Police officer",
    "Firefighter",
    "Chef",
    "Electrician",
    "Mechanic",
    "Pilot",
    "Journalist",
    "Dentist",
    "Pharmacist",
    "Accountant",
    "Designer",
    "Photographer",
    "Scientist",
    "Farmer",
    "Builder",
    "Waiter",
    "Driver",
    
    "Influencer",
    "TikTok creator",
    "Professional gamer",
    "Celebrity stylist",
    "Makeup artist",
    "Fashion model",
    "Art critic",
    "Astrologer",
    "Fortune teller",
    "DJ",
    "Stand-up comedian",
    "Travel blogger",
    "Luxury brand consultant",
    "Social media manager",
    "Wedding planner",
    "Magician",
    "Clown",
    "Voice actor",
    "Perfume tester",
    "Food critic"
]

hobbies = [
    # Useful for apocalypse
    "Fishing",
    "Hunting",
    "Gardening",
    "First aid training",
    "Fire making",
    "Knots tying",
    "Camping",
    "Water purification",
    "Archery",
    "Repairing tools",
    
    # Useless / funny in apocalypse
    "Watching TikTok",
    "Collecting stickers",
    "Doing makeup",
    "Scrolling social media",
    "Memorizing memes",
    "Celebrity gossip",
    "Online shopping",
    "Watching reality shows",
    "Selfie photography",
    "Following fashion trends"
]

health = [
    "Healthy",
    "Asthma",
    "Diabetes",
    "Broken leg",
    "Blind in one eye",
    "Allergy to dust",
    "Heart condition",
    "Strong immune system",
    "Chronic pain",
    "Anxiety"
]

items = [
    "Knife",
    "First aid kit",
    "Water bottle",
    "Gun (no ammo)",
    "Flashlight",
    "Rope",
    "Map",
    "Radio",
    "Battery pack",

    "Book",
    "Rubber duck",
    "Fancy hat",
    "Scented candle",
    "Luxury perfume",
    "Mirror",
    "Plush toy",
    "Chocolate bar (already melted)",
    "Deck of cards",
    "Magnet",
    "Feather",
    "Broken umbrella",
    "Sunglasses at night",
    "Empty notebook",
    "Toy sword",
    "Bottle of perfume",
    "Old VHS tape",
    "Glitter",
    "Plastic tiara",
    "Decorative rock",
    "Fake mustache"
]

special_traits = [
    "Knows a secret bunker location",
    "Has a hidden stash of food",
    "Former criminal",
    "Can speak 5 languages",
    "Afraid of darkness",
    "Infected but no symptoms",
    "Very lucky",
    "Extremely unlucky",
    "Hates everyone",
    "Trusted by all",

    "Expert at folding napkins",
    "Always loses socks",
    "Can talk to plants (they ignore you)",
    "Knows every meme from 2010",
    "Never remembers names",
    "Can balance spoon on nose",
    "Obsessed with cleaning shoes",
    "Laughs at their own jokes",
    "Always trips over nothing",
    "Can do 100 push-ups… once a month",
    "Collects bottle caps",
    "Can imitate animal sounds badly",
    "Always forgets why they entered a room",
    "Expert at making paper planes",
    "Can fold t-shirts in 2 seconds",
    "Talks to themselves",
    "Writes poetry no one reads",
    "Can juggle 2 objects",
    "Knows useless trivia about celebrities"
]

phobias = [
    "Fear of darkness",
    "Fear of heights",
    "Fear of water",
    "Fear of blood",
    "Fear of isolation",
    "Fear of insects",
    "Fear of loud noises",
    "Fear of fire",
    "Fear of small spaces",
    "Fear of strangers"
]
