# Generated by Django 5.2.12 on 2026-05-06 16:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='status',
            field=models.CharField(choices=[('waiting', 'Waiting'), ('in_game', 'In Game'), ('finished', 'Finished')], default='waiting', max_length=20),
        ),
        migrations.AlterField(
            model_name='friend',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lobby',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='lobbyinvitation',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('lobby', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='game', to='Bunker_App.lobby')),
            ],
        ),
        migrations.CreateModel(
            name='PlayerCharacter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=20)),
                ('height', models.CharField(max_length=20)),
                ('profession', models.CharField(max_length=100)),
                ('hobby', models.CharField(max_length=100)),
                ('health', models.CharField(max_length=100)),
                ('item', models.CharField(max_length=100)),
                ('special_trait', models.CharField(max_length=200)),
                ('phobia', models.CharField(max_length=100)),
                ('characteristics', models.JSONField(default=list)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='player_characters', to='Bunker_App.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='game_characters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
