# Generated by Django 5.2.12 on 2026-05-11 09:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Bunker_App.lobby'),
        ),
    ]
