# Generated by Django 6.0.3 on 2026-04-10 06:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lobby',
            name='user',
        ),
        migrations.AddField(
            model_name='lobby',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='created_lobbies', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lobby',
            name='participants',
            field=models.ManyToManyField(related_name='joined_lobbies', to=settings.AUTH_USER_MODEL),
        ),
    ]
