# Generated by Django 5.2.12 on 2026-05-11 09:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0002_alter_game_lobby'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='lobby',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='Bunker_App.lobby'),
        ),
    ]
