# Generated by Django 5.2.12 on 2026-05-07 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0002_lobby_status_alter_friend_id_alter_lobby_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
