# Generated by Django 5.2.12 on 2026-05-28 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0004_alter_game_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='current_turn_index',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='playercharacter',
            name='revealed_characteristics',
            field=models.JSONField(default=list),
        ),
    ]
