# Generated by Django 5.2.12 on 2026-06-04 10:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0009_lobbymessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vote',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes_received', to='Bunker_App.playercharacter'),
        ),
    ]
