# Generated by Django 5.2.12 on 2026-06-04 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0010_alter_vote_target'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='vote_phase',
        ),
        migrations.AddField(
            model_name='game',
            name='game_phase',
            field=models.CharField(default='revealing', max_length=20),
        ),
        migrations.DeleteModel(
            name='LobbyMessage',
        ),
    ]
