# Generated by Django 5.2.12 on 2026-06-28 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Bunker_App', '0012_lobbymessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='lobby',
            name='max_players',
            field=models.IntegerField(default=9),
        ),
        migrations.AddField(
            model_name='lobby',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('friends_only', 'Friends Only')], default='public', max_length=20),
        ),
    ]
